apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:HN2DTDuODMY=,iv:nZy2NjpkjQ6RDydS7Peh6tK4P3jKl8nM67lrF1swty4=,tag:ZbsMI8r3VZO2aBqbuMTUaw==,type:str]
    password: ENC[AES256_GCM,data:ce+48dCkU6NjhKVNh8oj5A==,iv:dfYEbeKVgECWrz3/QEYchaIbMRgqwxun60nPyeL0x/0=,tag:QH7EEjbsmQbmltVXDKyCEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1helqcqsh9464r8chnwc2fzj8uv7vr5ntnsft0tn45v2xtz0hpfwq98cmsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVGV3aDQ1UHFSQzkxQmVr
            K3YwMHd5ZW5mMFZ2dFRsYm1lblQ4c3RzaVJNCmEyemMvbllLZjErRlFscFg4Wmsv
            WDRwZ1JFZ1QyVC9IbzlIL2cwbU4vclUKLS0tIHlNTEs5ZlJHYVVGazJlcUNBVThP
            eTQ3aWFmWnRzQUFQUEM5ay84d1crbncKxbMA0hP4EwfycawMm7P0ZLWEjKA1efmN
            tk+S+ayjYN+Q2r+Jd9ltYgJ11Hb2+aBCf2tdJVM9Dd4zQ7MaICsEEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-30T16:06:53Z"
    mac: ENC[AES256_GCM,data:3ngxb6rFNWl5PA0mbJbLh3jMgrlZIjR9P0erRG6wDOT/R2Ne1tsBM+HeNPMGKWCbgVvsMfT4f3lzEOqmqCGL7wtisYUNuRDofqwUGx0k9IgV2RJwpZYie8Ms2s0M+716WD0CXrI/BXUk4Bs/ZRJAalUsahaTN90+xwIPaOfWonE=,iv:WA2VPtJJLDVSLPEmH7mHAAocpwUlIm/bvtS/Dvi/e98=,tag:pPJ4RYxvdlPdonP11gA2Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
